export {
  canChangeParticipationStatus,
  canEnterDeferred,
  educationStages,
  enrolmentAndTransitionEvents,
  episodeTerminalStatuses,
  evidenceVisibilityClasses,
  isEducationStage,
  isEnrolmentAndTransitionEvent,
  isEpisodeTerminal,
  isEpisodeTerminalStatus,
  isEvidenceVisibilityClass,
  isParticipationStatus,
  isTransitionGoal,
  isUnfoldStage,
  participationStatuses,
  participationStatusTransitions,
  transitionGoals,
  unfoldStages,
  type EducationStage,
  type EnrolmentAndTransitionEvent,
  type EpisodeTerminalStatus,
  type EvidenceVisibilityClass,
  type ParticipationStatus,
  type TransitionGoal,
  type UnfoldStage,
} from "./vocabulary";
