export const editorialImages = {
  "home-hero": {
    src: "/images/editorial/home-hero-guided-learning.jpg",
    width: 1600,
    height: 1004,
    alt: "Three young African women sit together and talk around a small basin. Stock photograph, not Mecellino Haven participants.",
    sizes: "(max-width: 768px) 90vw, 420px",
    objectPosition: "center 35%",
  },
  "home-pathway-ydg": {
    src: "/images/editorial/ydg-tracks-collaboration.jpg",
    width: 1600,
    height: 1067,
    alt: "Four young adults gather around a table to review a document. Stock photograph of collaborative discovery, not a YDG cohort.",
    sizes: "(max-width: 768px) 90vw, 540px",
    objectPosition: "center 42%",
  },
  "home-pathway-amusement": {
    src: "/images/editorial/amusement-portable-ringtoss.jpg",
    width: 1600,
    height: 1067,
    alt: "Adults play a portable ring-toss game on grass. Stock photograph of temporary recreation, not a Mecellino Haven venue.",
    sizes: "(max-width: 768px) 90vw, 540px",
    objectPosition: "center 55%",
  },
  "home-capacity": {
    src: "/images/editorial/institutional-document-review.jpg",
    width: 1600,
    height: 1067,
    alt: "Two adults review a document together. Stock photograph of facilitated professional training, not a Mecellino Haven class.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 28%",
  },
  "home-lifestyle": {
    src: "/images/editorial/lifestyle-guided-session.jpg",
    width: 1600,
    height: 1067,
    alt: "Two adults sit in a guided conversation. Stock photograph, not a coaching client or clinical session.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 28%",
  },
  "home-events": {
    src: "/images/editorial/events-traditional-gathering.jpg",
    width: 1600,
    height: 2399,
    alt: "Adults in traditional attire sit together at a celebration. Stock photograph, not a Mecellino Haven event listing.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 38%",
  },
  "home-amusement": {
    src: "/images/editorial/amusement-portable-ringtoss.jpg",
    width: 1600,
    height: 1067,
    alt: "Adults play a portable ring-toss game on grass. Stock photograph, not a permanent Mecellino Haven park.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 55%",
  },
  "capacity-hero": {
    src: "/images/editorial/institutional-document-review.jpg",
    width: 1600,
    height: 1067,
    alt: "Two adults review a document together. Stock photograph of facilitated professional training, not a Mecellino Haven class.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 28%",
  },
  "capacity-ydg": {
    src: "/images/editorial/ydg-tracks-collaboration.jpg",
    width: 1600,
    height: 1067,
    alt: "Four young adults gather around a table to review a document. Stock photograph, not enrolled YDG participants.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 42%",
  },
  "capacity-retirement": {
    src: "/images/editorial/retirement-professional-planning.jpg",
    width: 1600,
    height: 1067,
    alt: "A mature professional in a suit reviews documents. Stock photograph of later-life planning, not a coaching client.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 20%",
  },
  "capacity-individual": {
    src: "/images/editorial/individual-guided-discussion.jpg",
    width: 1600,
    height: 1067,
    alt: "Two women talk together on a sofa. Stock photograph of guided conversation, not a training client.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 30%",
  },
  "capacity-institutional": {
    src: "/images/editorial/institutional-document-review.jpg",
    width: 1600,
    height: 1067,
    alt: "Two adults review a document together. Stock photograph of professional discussion, not a partner organisation.",
    sizes: "(max-width: 768px) 90vw, 360px",
    objectPosition: "center 28%",
  },
  "ydg-hero": {
    src: "/images/editorial/ydg-tracks-collaboration.jpg",
    width: 1600,
    height: 1067,
    alt: "Four young adults gather around a table to review a document. Stock photograph of collaborative discovery, not a YDG cohort.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 42%",
  },
  "ydg-how-it-works": {
    src: "/images/editorial/individual-guided-discussion.jpg",
    width: 1600,
    height: 1067,
    alt: "Two women talk together on a sofa. Stock photograph of a mentoring conversation, not YDG participants.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 30%",
  },
  "ydg-tracks": {
    src: "/images/editorial/ydg-tracks-collaboration.jpg",
    width: 1600,
    height: 1067,
    alt: "Four young adults gather around a table to review a document. Stock photograph, not a YDG participant group.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 42%",
  },
  "lifestyle-hero": {
    src: "/images/editorial/lifestyle-guided-session.jpg",
    width: 1600,
    height: 1067,
    alt: "Two adults sit in a guided conversation. Stock photograph, not a coaching client or medical setting.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 28%",
  },
  "events-hero": {
    src: "/images/editorial/events-traditional-gathering.jpg",
    width: 1600,
    height: 2399,
    alt: "Adults in traditional attire sit together at a celebration. Stock photograph, not a ticketed Mecellino Haven festival.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 38%",
  },
  "amusement-hero": {
    src: "/images/editorial/amusement-portable-ringtoss.jpg",
    width: 1600,
    height: 1067,
    alt: "Adults play a portable ring-toss game on grass. Stock photograph of temporary recreation, not a permanent park.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 55%",
  },
  "about-hero": {
    src: "/images/editorial/about-independence-square.jpg",
    width: 3264,
    height: 2448,
    alt: "Independence Square in Accra, with the arch and open parade ground. Place-based photograph, not a Mecellino Haven facility.",
    sizes: "(max-width: 768px) 90vw, 38vw",
    objectPosition: "center 32%",
  },
} as const;

export type EditorialImageId = keyof typeof editorialImages;
